name: Auto build image
on:
  issue_comment:
    types:
      - created
jobs:
  issue_comment:
    name: Auto build image
    if: startswith(github.event.comment.body, '/bashbuild')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:

      - name: Check outputs
        run: |
          ls -R
          sudo cd / && sudo chmod 777 ./ -R
          sudo cd root
          wget https://sealer.oss-cn-beijing.aliyuncs.com/sealer-latest.tar.gz
          sudo tar -xvf sealer-latest.tar.gz -C /usr/bin
          sudo sealer login ${{secrets.PRIVATEWAREHOUSE}}
          sudo apt install git
          git clone https://github.com/AliyunContainerService/ackdistro.git
          cd ackdistro
          git checkout feature/v1.20.4-ack-3
          cd build
          ls -R
          bash build.sh te
          sudo sealer push ack-distro:te
      - name: Auto build image
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            auto-build successfully!
