# 钉钉 rss 推送机器人
name: DingDingRssBot

on:               
  schedule:                              # 设置定时任务
    - cron: '0 0/1 * * *'
    
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: dingtalk robot message
      uses: fifsky/dingtalk-action@master
      with:
        url: ${{ secrets.DINGTALK_WEBHOOK}}
        type: markdown
        content: |
          # Tips
          ## Hello
          > from github action message
          > ^_^
