name: Sealer-Mount-Test

on:
  issue_comment:
    types:
      - created
jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    if: startswith(github.event.comment.body, '/test mount')
    env:
      GO111MODULE: on
    steps:
      - name: Github API Request
        id: request
        uses: octokit/request-action@v2.0.2
        with:
          route: ${{ github.event.issue.pull_request.url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{fromJson(steps.request.outputs.data).head.repo.full_name}}
          ref: ${{fromJson(steps.request.outputs.data).head.ref}}
          path: src/github.com/alibaba/sealer

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libgpgme-dev libbtrfs-dev libdevmapper-dev
          sudo mkdir /var/lib/sealer
      - name: Set up Go 1.17
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
        id: go

      - name: Install sealer and ginkgo
        shell: bash
        run: |
          wget https://github.com/sealerio/sealer/releases/download/v0.9.1/sealer-v0.9.1-linux-amd64.tar.gz
          sudo tar -xvf sealer-v0.9.1-linux-amd64.tar.gz -C /usr/bin
          go install github.com/onsi/ginkgo/ginkgo@v1.16.2
          go install github.com/onsi/gomega/...@v1.12.0
          GOPATH=`go env GOPATH`
          echo "$GOPATH/bin" >> $GITHUB_PATH
          ll
          pwd
        #working-directory: src/github.com/sealerio/sealer

      - name: Run sealer image test
        shell: bash
        working-directory: src/github.com/sealerio/sealer
        if: ${{ github.event.comment.body == '/test mount' || github.event.comment.body == '/test all' || github.event_name == 'push' }}
        run: |
          ginkgo -v --focus="sealer mount" test