on:
  issue_comment:
    types:
      - created
name: Static page
jobs:
  build:
    runs-on: ubuntu-latest
    if:  ${{ github.event.comment.body == '/docs' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Update docs
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            update success!
