on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  issue_comment:
    types:
      - created

name: Static page
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{github.event.release.tag_name && github.event.comment.body == '/docs'}}
    steps:

      - name: test
        run: wget http://sealer.oss-cn-beijing.aliyuncs.com/auto-build/sealer.tar.gz
      - name: Update docs
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            update success!
#        with:
#          node-version: '14'
#      - run: npm install
#        working-directory: docs/site
#      - name: Static website hosting
#        run: npm run build
#        working-directory: docs/site
#      - name: Build static to oss
#        run: wget http://gosspublic.alicdn.com/ossutil/1.6.19/ossutil64 && chmod 755 ossutil64 &&
#          ./ossutil64 -i ${{ secrets.ACCESSKEYID }} -k ${{ secrets.ACCESSKEYSECRET }} -e oss-cn-beijing.aliyuncs.com cp -rf docs/site/src/.vuepress/dist oss://sealer/
